spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/dubbo_demo?useUnicode=true&characterEncoding=utf8&useSSL=false\
    &serverTimezone=Asia/Shanghai"
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.sun.common.bean
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: boot-payment-provider
  registry:
    protocol: zookeeper
    address: 192.168.126.30:2181
  protocol:
    port: 20880
    name: dubbo