server:
  port: 80
spring:
  redis:
    host: 192.168.126.20
    port: 6379
    password: zhaoyang
    database: 0
    timeout: PT600S
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 使用负数表示没有限制
        max-idle: 8 # 默认连接数最大空闲的连接数，默认为 8 使用负数表示没有限制
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 允许设置 0 和 正数
        max-wait: PT-1S # 连接池最大阻塞等待时间，单位：毫秒默认为 -1 ，表示不限制
