# redis相关配置
spring:
  redis:
    host: 192.168.126.10
    port: 6379
    database: 0
    timeout: PT20S # 连接超时时间（毫秒）
    jedis:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: PT-1S # 连接池最大阻塞等待时间（使用负值表示没有限制）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/redis_cache?useUnicode=true&characterEncoding=utf8\
    &useSSL=false&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456

mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

logging:
  level:
    com.sun.boot.mapper: debug
