server:
  port: 80

spring:
  datasource:
    # 数据库连接地址为 sharding-proxy 代理地址
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.126.20:3307/sharding_master_slave_db?serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
